# Generated by Django 2.2.5 on 2019-09-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volunteer', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
